name: TASK-MANAGEMENT-BACKEND | CI

on:
  push:
    branches:
      - main

jobs:
  test-lint:
    name: Test and List
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Test
        working-directory: backend
        run: python manage.py test

      - name: Run Lint
        working-directory: backend
        run: flake8
