name: Tasky Frontend CI

on:
  push:
    branches:
      - development
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install Dependencies
        working-directory: frontend
        run: npm install

      - name: Run Code Linting
        working-directory: frontend
        run: npm run lint

      - name: Run Code Format Checker
        working-directory: frontend
        run: npm run prettier:check

      - name: Build Code
        working-directory: frontend
        run: npm run build
